###Data###

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
filename = "/content/data.csv"

# Read the csv file
data = pd.read_csv(filename)

# Print the data
print(type(data))
data

<class 'pandas.core.frame.DataFrame'>


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  num  
0        3  0.0   6.0    0  
1        2  3.0   3.0    2  
2        2  2.0   7.0    1  
3        3  0.0   3.0    0  
4        1  0.0   3.0    0  
..     ...  ...   ...  ...  
298      2  0.0   7.0    1  
299      2  2.0   7.0    2  
300      2  1.0   7.0    3  
301      2  1.0   3.0    1  
302      1  NaN   3.0    0  

[303 rows x 14 columns]

Split the data, first 13 columns are training data, last colum is result we need to predict.

In [ ]:
# clean the data
data = data.dropna()
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
297   57    0   4       140   241    0        0      123      1      0.2   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   

     slope   ca  thal  num  
0        3  0.0   6.0    0  
1        2  3.0   3.0    2  
2        2  2.0   7.0    1  
3        3  0.0   3.0    0  
4        1  0.0   3.0    0  
..     ...  ...   ...  ...  
297      2  0.0   7.0    1  
298      2  0.0   7.0    1  
299      2  2.0   7.0    2  
300      2  1.0   7.0    3  
301      2  1.0   3.0    1  

[297 rows x 14 columns]

In [ ]:
# Selecting specific columns from the DataFrame
selected_columns_for_x = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
selected_columns_for_y = ['num']
x = data[selected_columns_for_x]
y = data[selected_columns_for_y]

correlation calculation start




In [ ]:
# Assuming df is your dataframe
from tabulate import tabulate
correlation_matrix = data.corr()
target_correlation = correlation_matrix[['num']]  # Replace 'target' with your target column name
print(tabulate(target_correlation, headers='keys', tablefmt='grid'))
# correlation_matrix['num']

+----------+------------+
|          |        num |
+==========+============+
| age      |  0.222156  |
+----------+------------+
| sex      |  0.226797  |
+----------+------------+
| cp       |  0.404248  |
+----------+------------+
| trestbps |  0.15962   |
+----------+------------+
| chol     |  0.0664482 |
+----------+------------+
| fbs      |  0.0490398 |
+----------+------------+
| restecg  |  0.184136  |
+----------+------------+
| thalach  | -0.420639  |
+----------+------------+
| exang    |  0.391613  |
+----------+------------+
| oldpeak  |  0.501461  |
+----------+------------+
| slope    |  0.374689  |
+----------+------------+
| ca       |  0.521178  |
+----------+------------+
| thal     |  0.513377  |
+----------+------------+
| num      |  1         |
+----------+------------+


In [ ]:
relevant_features = target_correlation[abs(target_correlation) > 0.05].index.tolist()

In [ ]:
for feature in relevant_features:
    correlated_vars = correlation_matrix[feature][(correlation_matrix[feature] > 0.5) | (correlation_matrix[feature] < -0.7)].index.tolist()
    correlated_vars.remove(feature)  # Remove the feature itself from the list
    if correlated_vars:
      if feature == 'num':
        print(f"{feature} is highly correlated with {correlated_vars}")

num is highly correlated with ['oldpeak', 'ca', 'thal']


correlation calculation end

In [ ]:
one_hot_y = pd.get_dummies(data['num'], prefix='num')
one_hot_y

num_0  num_1  num_2  num_3  num_4
0        1      0      0      0      0
1        0      0      1      0      0
2        0      1      0      0      0
3        1      0      0      0      0
4        1      0      0      0      0
..     ...    ...    ...    ...    ...
297      0      1      0      0      0
298      0      1      0      0      0
299      0      0      1      0      0
300      0      0      0      1      0
301      0      1      0      0      0

[297 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, one_hot_y, test_size=0.2, random_state=0)

In [ ]:
x_train.shape

(237, 13)

In [ ]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
286   58    0   4       170   225    1        2      146      1      2.8   
81    53    0   4       130   264    0        2      143      0      0.4   
109   39    1   4       118   219    0        0      140      0      1.2   
147   41    1   3       112   250    0        0      179      0      0.0   
220   41    0   3       112   268    0        2      172      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
254   43    1   4       115   303    0        0      181      0      1.2   
195   67    1   4       100   299    0        2      125      1      0.9   
118   63    1   4       130   330    1        2      132      1      1.8   
47    50    1   4       150   243    0        2      128      0      2.6   
174   64    1   4       145   212    0        2      132      0      2.0   

     slope   ca  thal  
286      2  2.0   6.0  
81       2  0.0   3.0  
109      2  0.0   7.0  
147      1  0.0   3.0  
220      1  0.0   3.0  
..     ...  ...   ...  
254      2  0.0   3.0  
195      2  2.0   3.0  
118      1  3.0   7.0  
47       2  0.0   7.0  
174      2  2.0   6.0  

[237 rows x 13 columns]

In [ ]:
y_train.shape

(237, 5)

In [ ]:
y_train

num_0  num_1  num_2  num_3  num_4
286      0      0      1      0      0
81       1      0      0      0      0
109      0      0      0      1      0
147      1      0      0      0      0
220      1      0      0      0      0
..     ...    ...    ...    ...    ...
254      1      0      0      0      0
195      0      0      0      1      0
118      0      0      0      1      0
47       0      0      0      0      1
174      0      0      0      0      1

[237 rows x 5 columns]

Data cleaning finished, models go from here

###Use one-hot###

In [ ]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
model = MultiOutputRegressor(LinearRegression())
model.fit(x_train, y_train)

MultiOutputRegressor(estimator=LinearRegression())

In [ ]:
# Predict
y_pred = model.predict(x_test)

In [ ]:
# Evaluate
mse = mean_squared_error(y_test, y_pred, multioutput='raw_values')
for i, err in enumerate(mse, 1):
    print(f"Output {i} MSE: {err:.2f}")

Output 1 MSE: 0.14
Output 2 MSE: 0.16
Output 3 MSE: 0.11
Output 4 MSE: 0.07
Output 5 MSE: 0.08


####old model###

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
print("Intercept: ", model.intercept_)
print("Coefficients: ")
list(zip(x,model.coef_))

Intercept:  [ 1.57877605 -0.4750378  -0.08617746  0.19955213 -0.21711291]
Coefficients: 


[('age',
  array([ 0.00032829, -0.12214787, -0.10150037, -0.00336119, -0.00043837,
          0.08234232, -0.02427066,  0.0030206 , -0.16184279, -0.02575228,
         -0.05063993, -0.11527269, -0.06048856])),
 ('sex',
  array([ 2.92781078e-03,  1.04215884e-01,  1.30018514e-02,  1.52570779e-03,
          4.01017076e-04, -1.49596995e-01,  6.83881583e-03,  3.24001526e-05,
          1.06517895e-01, -4.84114671e-02,  2.64454733e-02, -5.08036410e-03,
          1.40505594e-02])),
 ('cp',
  array([ 0.00182827,  0.04217237,  0.02789404, -0.00017372,  0.00034242,
          0.03920343, -0.04167132, -0.00109271,  0.07658939,  0.05640842,
         -0.01734576,  0.0113021 ,  0.01252674])),
 ('trestbps',
  array([-0.00481334, -0.01685525,  0.03653007,  0.00074158, -0.00022834,
          0.06726414,  0.03849387, -0.00148372,  0.044587  ,  0.01858388,
          0.0168616 ,  0.08077295,  0.01996797])),
 ('chol',
  array([-2.71028753e-04, -7.38513566e-03,  2.40744060e-02,  1.26762311e-03,
         -7.6718

In [ ]:
y_pred = model.predict(x_test)
print("Prediction for test set: {}".format(y_pred))

Prediction for test set: [[ 9.55202737e-01  2.06076750e-01 -1.28338842e-01 -3.74207988e-02
   4.48015474e-03]
 [ 7.49327735e-01  4.54555679e-02 -4.71235514e-03  1.59393281e-01
   5.05357708e-02]
 [ 3.27281450e-01  2.11409833e-01  1.70036855e-01  2.84294032e-01
   6.97782943e-03]
 [ 7.56455008e-01  2.61321234e-01 -1.77206101e-02 -3.09972474e-02
   3.09416162e-02]
 [ 8.06979651e-01  3.10575154e-01  8.86238471e-02 -9.68507994e-02
  -1.09327852e-01]
 [ 7.47707872e-01  1.39766625e-01 -4.88537129e-02  1.25527597e-01
   3.58516180e-02]
 [ 6.28344081e-01  1.08852630e-01  2.56679086e-01  9.12294860e-02
  -8.51052832e-02]
 [ 6.61887929e-01  1.85807007e-01  6.50236892e-02  2.10702505e-02
   6.62111242e-02]
 [ 6.33097758e-02  2.43248894e-01  1.85321444e-01  3.19338337e-01
   1.88781548e-01]
 [ 5.83508779e-01  2.39806696e-01 -1.22328579e-03  1.60785354e-01
   1.71224567e-02]
 [ 3.62663822e-01  2.29111354e-01  1.10492107e-01  1.92819798e-01
   1.04912919e-01]
 [ 8.45289644e-01  1.28072315e-01  9.571

In [ ]:
from sklearn import metrics

meanAbErr = metrics.mean_absolute_error(y_test,y_pred)
meanSqErr = metrics.mean_squared_error(y_test,y_pred)
rootMeanSqErr = np.sqrt(meanSqErr)

print('R squared: {:.2f}'.format(model.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

ValueError: ignored

###Logistic Regression###

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# instantiate the model (using the default parameters)
logreg = LogisticRegression(solver='sag', max_iter=100)

In [ ]:
# fit the model with data
logreg.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(solver='sag')

In [ ]:
y_pred = logreg.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0])

In [ ]:
y_test.T

112  151  12   219  140  74   211  173  189  217  ...  55   285  282  \
num    0    0    2    0    0    1    4    0    2    0  ...    1    4    3   

     26   66   223  230  250  59   295  
num    0    1    3    0    0    0    0  

[1 rows x 60 columns]

In [ ]:
from sklearn import metrics

meanAbErr = metrics.mean_absolute_error(y_test,y_pred)
meanSqErr = metrics.mean_squared_error(y_test,y_pred)
rootMeanSqErr = np.sqrt(meanSqErr)

print('R squared: {:.2f}'.format(model.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

R squared: 55.34
Mean Absolute Error: 0.9333333333333333
Mean Square Error: 2.466666666666667
Root Mean Square Error: 1.570562531918633


In [ ]:
score = logreg.score(x_test, y_test)
print(score)

0.5333333333333333


In [ ]:
!pip install ucimlrepo

In [ ]:
#print(y.head())
print(X.head())

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  
0  0.0   6.0  
1  3.0   3.0  
2  2.0   7.0  
3  0.0   3.0  
4  0.0   3.0  


###treat this project as 2 classes classification, disease/no disease###

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.impute import SimpleImputer
from ucimlrepo import fetch_ucirepo

# Fetch the heart disease dataset from UCI Repository
heart_disease = fetch_ucirepo(id=45)

# Assign feature matrix and target values
X = heart_disease.data.features
y = heart_disease.data.targets

# Handle missing values by imputation
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2)

# Train a linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(meanSqErr)

# Print evaluation metrics
print('R squared: {:.2f}%'.format(model.score(X_test, y_test) * 100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

# Print metadata and variable information (optional)
print('\nMetadata:\n', heart_disease.metadata)
print('\nVariable Information:\n', heart_disease.variables)


R squared: 48.23%
Mean Absolute Error: 0.6029089214255725
Mean Square Error: 0.5688099880171484
Root Mean Square Error: 0.7541949270693542

Metadata:
 {'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Life Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'title': 'International application of a new probab

In [ ]:
pip install ucimlrepo

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import SimpleImputer
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

# Fetch the heart disease dataset from UCI Repository
heart_disease = fetch_ucirepo(id=45)

# Assign feature matrix and target values
X = heart_disease.data.features

# get rid of null values
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Convert to binary outcome: 0 (no heart disease) and above 0 (heart disease)
y = heart_disease.data.targets['num'].apply(lambda x: 1 if x > 0 else 0)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2)

# Train a logistic regression classifier
classifier = LogisticRegression(max_iter=10000)
classifier.fit(X_train, y_train)

# Predict on test data
y_pred = classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.819672131147541
              precision    recall  f1-score   support

           0       0.75      0.89      0.81        27
           1       0.90      0.76      0.83        34

    accuracy                           0.82        61
   macro avg       0.82      0.83      0.82        61
weighted avg       0.83      0.82      0.82        61



In [ ]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  
0        3  0.0   6.0  
1        2  3.0   3.0  
2        2  2.0